### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelectorAll')

### ISSUE THREAD

**Issue by lookfirst** [plibither8/refined-hacker-news#124]
```refined-hacker-news.js:2756 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at getGroupedStories (refined-hacker-news.js:2756:32)
    at requestVisitedStories (refined-hacker-news.js:2909:21)
    at hide_read_stories_init (refined-hacker-news.js:2960:5)
    at refined-hacker-news.js:3026:17
    at new Promise (<anonymous>)
    at Object.add (refined-hacker-news.js:3022:12)
    at initialiseAll (refined-hacker-news.js:5131:24)```

**Comment by plibither8** [comment]
Thanks @lookfirst, got this error too - looking into it!

**Comment by lookfirst** [comment]
Thank you sir. I'd submit PR's but I honestly can't work in JS... I'm so used to TS... would you be open to a conversion?

**Comment by plibither8** [comment]
@lookfirst sure! I've been contemplating for I don't know how long to do a massive refactor and rewrite the extension in TS. Would LOVE help with that too. Till then if you have capacity to look into this error and try your hand at it, I'd love to help you out! 🙂

**Comment by theY4Kman** [comment]
It looks like `table.itemlist` is no longer an appropriate selector to get the `<table>` holding the stories. There doesn't appear to be any unique identifier on that table at all, any more. I've been testing out `#hnmain table:has(.athing)` as the selector instead.

**Comment by plibither8** [comment]
Thanks for the headsup @theY4Kman, I'll hopefully get time this weekend to deepdive into the issue, but the scope itself seems pretty large and would require a large-scale refactor... not looking forward. 😔

**Comment by lookfirst** [comment]
Try emailing @dang and asking him to add it back or make it simpler? I bet
he would be responsive.

**Comment by lookfirst** [comment]
Oddly, ran across this whole blog post on `:has`

https://webkit.org/blog/13096/css-has-pseudo-class/

**Comment by lookfirst** [comment]
@plibither8 you forget me? ;-)

**Comment by fnordson** [comment]
I ran into the same issue.  
Can someone here tell me if it's what causes the sorting to break because it hasn't been working for quite a while now. 
(Firefox 108.0.1 @ windows10)

**Comment by lookfirst** [comment]
The way this extension is coded, it breaks everything.

**Comment by compuguy** [comment]
This still seems to be an issue.

**Comment by fnordson** [comment]
I'd guess, this thing is dead.

**Comment by lookfirst** [comment]
The extension mostly works with my PR applied to it. https://github.com/plibither8/refined-hacker-news/pull/125

It does seem dead, which is ok. It really does need a full rewrite.

I've been collecting notes on what a future version of this extension would look like, at some point, I'll find the time/motivation to start coding.
